name: image-style-transfer
services:
  redis:
    container_name: redis
    image: redis:latest

  web:
    container_name: web
    build: ./web
    volumes:
      - ./web:/app
    ports:
      - 3000:80

  worker:
    container_name: worker
    build: ./backend
    command: celery -A worker.worker worker -l INFO -P eventlet -c 1
    volumes:
      - ./backend:/code
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - api
      - redis

  api:
    container_name: api
    build: ./backend
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/code
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
