# FROM node:16

# WORKDIR /app

# ENV NODE_PATH /app/node_modules

# COPY package.json .

# RUN npm install

# COPY . .

# RUN npm run build

FROM node:16 AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html/
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]